version: "3.7"
services:
  php72:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    ports:
      - "127.0.0.1:9000:9000"
    extra_hosts:
      - "fend.javfree.me:139.162.107.149"
    volumes:
      - /home/wwwroot/:/home/wwwroot/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php72
      - net-redis

  redis:
    image: redislabs/redisearch:latest
    restart: always
    networks:
      - net-redis
    ports:
      - "127.0.0.1:6379:6379"

networks:
  net-php72:
  net-redis:
