version: "3.7"
services:

  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

networks:
  net-mysql:
